/* Replace with your SQL commands */
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  login VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(65) NOT NULL UNIQUE,
  name VARCHAR(30) NOT NULL,
  surname VARCHAR(30) NOT NULL,
  tagname VARCHAR(30) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  is_online BOOLEAN,
  last_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);